import { type NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import StateWrapper from "../components/common/StateWrapper";
import RecipesListing from "../components/Recipe/RecipesListing";
import MainLayout from "../components/ui/MainLayout";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const infiniteRecipesQuery = api.recipe.infiniteRecipes.useInfiniteQuery({}, {
    getNextPageParam: (lastPage) => lastPage.nextCursor
  })

  const recipeQuery = api.recipe.getOneById.useQuery({ id: 1 })

  const handleSignIn = () => {
    void signIn('discord')
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout useContainer={true}>
        <StateWrapper
          isLoading={infiniteRecipesQuery.isLoading}
          isError={infiniteRecipesQuery.isError}
          data={infiniteRecipesQuery.data?.pages[0]?.recipes}
          NonEmpty={data => <RecipesListing recipes={data} />}
        />
      </MainLayout>
    </>
  );
};

export default Home
